/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -O3   -I/Users/sandy/.choosenim/toolchains/nim-1.6.6/lib -I/Users/sandy/work/x-language-review/lrnim -o /Users/sandy/work/x-language-review/lrnim/@mref.nim.c.o /Users/sandy/work/x-language-review/lrnim/@mref.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q {
NI x;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
static N_NIMCALL(void, Marker_tyRef__9cAJRFBeW3VV9akcEy3Fb2dw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__dyq9c9as65rqkNRR9bopdoA7Q_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, refDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE TNimType NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIt__9cAJRFBeW3VV9akcEy3Fb2dw_;
N_LIB_PRIVATE tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q* t__ref_4;
static N_NIMCALL(void, Marker_tyRef__9cAJRFBeW3VV9akcEy3Fb2dw)(void* p, NI op) {
	tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q* a;
	a = (tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q*)p;
}
static N_NIMCALL(void, TM__dyq9c9as65rqkNRR9bopdoA7Q_2)(void) {
	nimGCvisit((void*)t__ref_4, 0);
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	refDatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__dyq9c9as65rqkNRR9bopdoA7Q_2);

}/* preInitProc end */
{
	tyArray__nHXaesL0DJZHyVS07ARPRA T1_;
	nimZeroMem((void*)T1_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T1_[0] = dollar___systemZdollars_3((*t__ref_4).x);
	echoBinSafe(T1_, 1);
}
}

N_LIB_PRIVATE N_NIMCALL(void, refDatInit000)(void) {
static TNimNode TM__dyq9c9as65rqkNRR9bopdoA7Q_0[1];
NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_.size = sizeof(tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q);
NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_.align = NIM_ALIGNOF(tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q);
NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_.kind = 18;
NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_.base = 0;
NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_.flags = 1;
TM__dyq9c9as65rqkNRR9bopdoA7Q_0[0].kind = 1;
TM__dyq9c9as65rqkNRR9bopdoA7Q_0[0].offset = offsetof(tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q, x);
TM__dyq9c9as65rqkNRR9bopdoA7Q_0[0].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__dyq9c9as65rqkNRR9bopdoA7Q_0[0].name = "x";
NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_.node = &TM__dyq9c9as65rqkNRR9bopdoA7Q_0[0];
NTIt__9cAJRFBeW3VV9akcEy3Fb2dw_.size = sizeof(tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q*);
NTIt__9cAJRFBeW3VV9akcEy3Fb2dw_.align = NIM_ALIGNOF(tyObject_TcolonObjectType___j7dPD2uvkFNzf17iqhz67Q*);
NTIt__9cAJRFBeW3VV9akcEy3Fb2dw_.kind = 22;
NTIt__9cAJRFBeW3VV9akcEy3Fb2dw_.base = (&NTIt58objecttype__j7dPD2uvkFNzf17iqhz67Q_);
NTIt__9cAJRFBeW3VV9akcEy3Fb2dw_.marker = Marker_tyRef__9cAJRFBeW3VV9akcEy3Fb2dw;
}

